### ISSUE TITLE
Redaxo-Frage vom Kunden

### ISSUE THREAD

**Issue by GrafikDimo** [Tapetenwechsel-Leipzig/christian-kortuem.de#1]
Der Kunde will gern wissen, nach welchem Prinzip die Bilder der Seite "Foto" bzw. die Clips der Seite "Video" angezeigt werden?

Wenn man auf die Unterseite in Redaxo geht, scheint da xix drin zu sein (bei "Video" das selbe)
![ck_redaxo1](https://github.com/Tapetenwechsel-Leipzig/christian-kortuem.de/assets/137283793/4707503e-9067-4851-b46d-e46a281ae803)

**Comment by IngoWinter** [comment]
Das Video ist in den Artikel Metas (Eigenschaften) hinterlegt, das Bild wird zufällig aus der Medienpoolkategorie 2 ausgesucht.
